name: easy_downloader
description: Easy Downloader is a simple and easy to use plugin to download files from the internet.
version: 0.0.13
homepage: https://github.com/linkkader/easy_downloader/blob/main/example/lib/main.dart
repository: https://github.com/linkkader/easy_downloader

environment:
  sdk: '>=2.18.0 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.0.11
  flutter:
    sdk: flutter

dev_dependencies:
  hive_generator: ^1.1.3
  build_runner: ^2.1.8
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0


flutter:
  generate: true