name: easy_downloader_flutter_lib
description: flutter libs for easy_downloader
version: 0.0.16
homepage: https://github.com/linkkader/easy_downloader/blob/main/example/bin/example.dart
repository: https://github.com/linkkader/easy_downloader

environment:
  sdk: '>=2.19.2 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  isar_flutter_libs: ^3.0.5
  flutter_local_notifications: ^13.0.0
  easy_downloader: ^0.0.16
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
